version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - ./.env